// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HeroDocumentDataSlicesSlice = TestSlice;

/**
 * Content for Hero documents
 */
interface HeroDocumentData {
  /**
   * Slice Zone field in *Hero*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeroDocumentDataSlicesSlice> /**
   * Meta Description field in *Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hero.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hero*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hero.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Hero document from Prismic
 *
 * - **API ID**: `hero`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeroDocumentData>, "hero", Lang>;

/**
 * Content for Hero Rubrik documents
 */
interface HeroRubrikDocumentData {
  /**
   * Om griaffen field in *Hero Rubrik*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_rubrik.om_griaffen
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  om_griaffen: prismic.KeyTextField;

  /**
   * Ingress field in *Hero Rubrik*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text om giraffen
   * - **API ID Path**: hero_rubrik.ingress
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ingress: prismic.KeyTextField;
}

/**
 * Hero Rubrik document from Prismic
 *
 * - **API ID**: `hero_rubrik`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeroRubrikDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HeroRubrikDocumentData>,
    "hero_rubrik",
    Lang
  >;

export type AllDocumentTypes = HeroDocument | HeroRubrikDocument;

/**
 * Primary content in *Test → Primary*
 */
export interface TestSliceDefaultPrimary {
  /**
   * dsfsd field in *Test → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: sdfsdf
   * - **API ID Path**: test.primary.dsfsd
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dsfsd: prismic.RichTextField;
}

/**
 * Default variation for Test Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Test*
 */
type TestSliceVariation = TestSliceDefault;

/**
 * Test Shared Slice
 *
 * - **API ID**: `test`
 * - **Description**: Test
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSlice = prismic.SharedSlice<"test", TestSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeroDocument,
      HeroDocumentData,
      HeroDocumentDataSlicesSlice,
      HeroRubrikDocument,
      HeroRubrikDocumentData,
      AllDocumentTypes,
      TestSlice,
      TestSliceDefaultPrimary,
      TestSliceVariation,
      TestSliceDefault,
    };
  }
}
